backend:
  name: github
  repo: manager-dev/johan-kepler-web
  branch: develop
  base_url: https://auth-cms.portalweb.cc
  auth_endpoint: auth

# Comentar o eliminar local_backend para entorno remoto
# local_backend: true

media_folder: "public/images/noticias"
public_folder: "/images/noticias"

collections:
  - name: "noticias"
    label: "Boletín y Avisos"
    folder: "src/content/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - {
        label: "Categoría",
        name: "category",
        widget: "select",
        options: ["Aviso Importante", "Académico", "Feria de Logros", "Deportes", "Comunidad", "Pastoral"],
        default: "Comunidad"
      }
      - { label: "Aviso Urgente (Franja Superior)", name: "urgent", widget: "boolean", default: false, required: false }
      - { label: "Imagen Destacada", name: "image", widget: "image", required: false }
      - { label: "Resumen Corto", name: "summary", widget: "string", required: false }
      - { label: "Cuerpo de la Noticia", name: "body", widget: "markdown" }